"use client";
import { useState } from 'react';

export default function Home() {
  const [formData, setFormData] = useState({ name: '', college: '', year: '1st Year', cgpa: '' });
    const [result, setResult] = useState(null);

      const handleSubmit = (e) => {
          e.preventDefault();
              
                  // Temporary mock algorithm until we connect the database
                      let baseLimit = 500;
                          if (formData.college.toUpperCase().includes('IIT') || formData.college.toUpperCase().includes('AIIMS') || formData.college.toUpperCase().includes('NIT')) baseLimit += 1000;
                              if (formData.year === 'Final Year' || formData.year === '3rd Year') baseLimit += 500;
                                  if (parseFloat(formData.cgpa) >= 8.5) baseLimit += 500;
                                      
                                          setResult(Math.min(baseLimit, 2500));
                                            };

                                              return (
                                                  <div className="min-h-screen bg-gray-900 text-white flex flex-col items-center justify-center p-4 font-sans">
                                                        <div className="text-center max-w-xl mb-10">
                                                                <h1 className="text-4xl md:text-5xl font-extrabold mb-4 text-blue-400 tracking-tight">Credology</h1>
                                                                        <p className="text-lg text-gray-300">Unlock India's first student-only digital credit line. No CIBIL required. Check your future credit score below.</p>
                                                                              </div>

                                                                                    {!result ? (
                                                                                            <form onSubmit={handleSubmit} className="bg-gray-800 p-8 rounded-2xl shadow-2xl border border-gray-700 w-full max-w-md">
                                                                                                      <div className="mb-4">
                                                                                                                  <label className="block text-sm font-medium text-gray-400 mb-1">Full Name</label>
                                                                                                                              <input className="w-full p-3 rounded-lg bg-gray-900 border border-gray-600 text-white focus:border-blue-500 focus:outline-none" type="text" required onChange={(e) => setFormData({...formData, name: e.target.value})} />
                                                                                                                                        </div>
                                                                                                                                                    
                                                                                                                                                              <div className="mb-4">
                                                                                                                                                                          <label className="block text-sm font-medium text-gray-400 mb-1">College Name (e.g. AIIMS, IIT Bombay)</label>
                                                                                                                                                                                      <input className="w-full p-3 rounded-lg bg-gray-900 border border-gray-600 text-white focus:border-blue-500 focus:outline-none" type="text" required onChange={(e) => setFormData({...formData, college: e.target.value})} />
                                                                                                                                                                                                </div>
                                                                                                                                                                                                            
                                                                                                                                                                                                                      <div className="mb-4">
                                                                                                                                                                                                                                  <label className="block text-sm font-medium text-gray-400 mb-1">Year of Study</label>
                                                                                                                                                                                                                                              <select className="w-full p-3 rounded-lg bg-gray-900 border border-gray-600 text-white focus:border-blue-500 focus:outline-none" onChange={(e) => setFormData({...formData, year: e.target.value})}>
                                                                                                                                                                                                                                                            <option>1st Year</option><option>2nd Year</option><option>3rd Year</option><option>Final Year</option>
                                                                                                                                                                                                                                                                        </select>
                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                            <div className="mb-8">
                                                                                                                                                                                                                                                                                                        <label className="block text-sm font-medium text-gray-400 mb-1">Current CGPA / Percentage</label>
                                                                                                                                                                                                                                                                                                                    <input className="w-full p-3 rounded-lg bg-gray-900 border border-gray-600 text-white focus:border-blue-500 focus:outline-none" type="number" step="0.1" max="10" required onChange={(e) => setFormData({...formData, cgpa: e.target.value})} />
                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                        <button className="w-full bg-blue-600 hover:bg-blue-500 text-white font-bold py-3 px-4 rounded-lg transition-colors shadow-lg">
                                                                                                                                                                                                                                                                                                                                                    Calculate My Limit
                                                                                                                                                                                                                                                                                                                                                              </button>
                                                                                                                                                                                                                                                                                                                                                                      </form>
                                                                                                                                                                                                                                                                                                                                                                            ) : (
                                                                                                                                                                                                                                                                                                                                                                                    <div className="bg-gray-800 border-2 border-green-500 p-8 rounded-2xl shadow-2xl text-center w-full max-w-md transition-all">
                                                                                                                                                                                                                                                                                                                                                                                              <h2 className="text-xl font-bold text-green-400 mb-2">Pre-Approval Successful</h2>
                                                                                                                                                                                                                                                                                                                                                                                                        <p className="text-gray-400 mb-2">Your calculated digital limit is:</p>
                                                                                                                                                                                                                                                                                                                                                                                                                  <p className="text-6xl font-extrabold text-white mb-6 tracking-tighter">₹{result}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                            <p className="text-sm text-gray-300 mb-6 bg-gray-900 p-4 rounded-lg">You have been added to the waitlist. We will notify you when the Credology network goes live on your campus.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                      <button onClick={() => setResult(null)} className="text-blue-400 text-sm hover:underline">← Check another profile</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                    )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                            